---
# Ansible
ansible_user: iaas
ansible_become: True

# Himlar
himlar_path: /opt/himlar
himlar_repo: https://github.com/norcams/himlar.git
himlar_ref: master
himlar_force_update: yes
himlar_update_secrets: True

# Himlar CLI
himlarcli_path: /opt/himlarcli
himlarcli_repo: https://github.com/norcams/himlarcli.git
himlarcli_ref: master
himlarcli_force_update: yes
himlarcli_packages:
  - python3-virtualenv
  - python3-pyyaml
  - git
  - gcc
  - openldap-devel
  - openssl-devel
  - libffi-devel

# imagebuilder
imagebuilder_path: /opt/imagebuilder
imagebuilder_repo: https://github.com/trondham/imagebuilder.git
imagebuilder_ref: major_refactor
imagebuilder_force_update: yes

# puppet environments for puppetmaster
puppet_environments:
  - admin
  - monitor
  - controller
  - el9
  - wallaby
  - xena
  - yoga
  - yoga_el9
  - zed

# Secrets to sync
secret_files: {}
