---
http_proxy:  "172.28.0.97:8888"
https_proxy: "172.28.0.97:8888"
secret_files:
  config:
    path:  '/var/lib/nova/.ssh/config'
    mode:  '0644'
    owner: 'nova'
    group: 'nova'
  id_rsa:
    path:  '/var/lib/nova/.ssh/id_rsa'
    mode:  '0600'
    owner: 'nova'
    group: 'nova'
